#version 430

uniform int u_NbOfParticles;

layout(std430, binding=2) buffer colors{
   float channels[];
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
void main(){
    uint gid = gl_GlobalInvocationID.x;
    if (gid < u_NbOfParticles) {
        float t = gid / float(u_NbOfParticles);
        vec3 col = vec3(t, 0, 1-t);
        channels[3 * gid    ] = col.r;
        channels[3 * gid + 1] = col.g;
        channels[3 * gid + 2] = col.b;
    }
}