#version 430

uniform int u_NbOfParticles;
uniform float u_Seed;

layout(std430, binding=1) buffer restPositions{
   vec2 restPos[];
};

float rand(vec2 co){
  return 2.0 * fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453) - 1.0;
}

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
void main(){
    uint gid = gl_GlobalInvocationID.x;

    if (gid < u_NbOfParticles) {
        restPos[gid] = vec2(rand(vec2(gid, u_Seed)), rand(vec2(gid, u_Seed + 12345.45678)));
    }
}