uniform int u_NbOfParticles;
// Params
uniform int u_count;
uniform int u_intLR;
uniform int u_intUD;
uniform float u_wheel;
uniform float u_ctrlWheel;
uniform float u_shiftWheel;
uniform float u_altWheel;
//Rand
uniform float u_Seed;
uniform float a;
uniform vec2 v;
uniform vec2 xyOff;
uniform float delta;

vec2 shape(float t, vec2 center, float radius) {
	float angle = t * 6.28;
	return center + radius * vec2(cos(angle), sin(angle));
}