//? #version 430

uniform int u_NbOfParticles;
uniform float u_aspectRatio;
// Parameters
uniform int u_LR;
uniform int u_ctrlWheel;
uniform int u_wheel;	 
uniform int u_shiftWheel;
uniform int u_altWheel;	 
uniform int u_count;	 
uniform int u_UD;		 
// Random
uniform float u_seed;
uniform vec2 u_xySeed;
//? float rand(float id, float seed);

vec2 shape(float t, vec2 center, float radius, float rotation) {
	return center;
}