//? #version 430

uniform int u_NbOfParticles;
uniform float u_aspectRatio;
// Params
uniform int u_LR;
uniform int u_UD;
uniform int u_wheel;
uniform int u_ctrlWheel;
uniform int u_shiftWheel;
uniform int u_altWheel;
// Random
uniform float u_seed;
uniform vec2 u_xySeed;
//? float rand(float id, float seed);

vec2 getPosition(uint particleID) {
    return vec2(
        rand(particleID, u_seed + u_xySeed.y),
        rand(particleID, u_seed + u_xySeed.x)
    );
}