#version 430

uniform int u_NbOfParticles;
uniform vec2 u_position;

struct particle{
    vec2 pos;
    vec2 vel;
};

layout(std430, binding=0) buffer particles{
   particle part[];
};
layout(std430, binding=1) buffer restPositions{
   vec2 restPos[];
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
void main(){
    uint gid = gl_GlobalInvocationID.x;
    if (gid < u_NbOfParticles) {
        part[gid].pos = restPos[gid];
        part[gid].vel = vec2(0.);
    }
}