//? #version 430
//? vec2 shape(float t, vec2 center, float radius, float rotation);

// Included by the shape
//? uniform int u_NbOfParticles;

layout(std430, binding=4) buffer positionsBuffer {
   vec2 positions[];
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
void main(){
    uint gid = gl_GlobalInvocationID.x;
    if (gid < u_NbOfParticles) {
        positions[gid] = shape(gid / float(u_NbOfParticles), vec2(0.0), 0.95, 0.0);
    }
}