//? #version 430

uniform int u_NbOfParticles;
uniform float u_aspectRatio;
// Params
uniform int u_count;
uniform int u_LR;
uniform int u_UD;
uniform float u_wheel;
uniform float u_ctrlWheel;
uniform float u_shiftWheel;
uniform float u_altWheel;
// Random
uniform float u_seed;
uniform vec2 u_xySeed;
float rand(float id, float seed);
vec2 getPosition(uint particleID);

vec2 shape(float t, vec2 center, float radius, float rotation) {
	return center + radius * vec2(cos(t*6.28), sin(t*6.28));
}